[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "gapnet"
authors = [{name = "Jens Lindahl", email = "jensctl@gmail.com"}]
dynamic = ["version", "description"]